module.exports = ["We must accept finite disappointment, but we must never lose infinite hope."
, "Don’t grieve. Anything you lose comes round in another form."
, "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live."
, "There is no pain so great as the memory of joy in present grief."
, "Worry does not empty tomorrow of its sorrow. It empties today of its strength."
, "Flowers grow out of dark moments."
, "From the end spring new beginnings."
, "We should feel sorrow, but not sink under its oppression."
, "Not without hope we suffer and we mourn."
, "Sorrow is so easy to express and yet so hard to tell."
, "The dew of compassion is a tear."
, "Sympathy is two hearts tugging at one load."];
