module.exports = ["If you could be either God’s worst enemy or nothing, which would you choose?"
, "The point is there ain't no point."
, "I like the idea of a black sun; like a black hole in space,"
+ "sucking everything into darkness, where we came from and where we're heading"
, "If we believe in nothing, if nothing has any meaning and if we can affirm no values whatsoever,"
+ "then everything is possible and nothing has any importance."
, "Why do we argue? Life's so fragile, a successful virus clinging to a speck of mud, suspended in endless nothing."
, "There is no other world. Nor even this one. What, then, is there?"
+ "The inner smile provoked in us by the patent nonexistence of both."
, "Sometimes I wish I had not woken up from a beautiful dream, and continued dreaming within sleep upon"
+ "sleep until I become a dream itself. Because sometimes waking up is more frightening than a nightmare."
, "From a cosmic perspective, I'm simply an accident that has nothing to lose. Why take it all so seriously?"
, "Hell is other people"
, "Human race spoilers: we go extinct and none of this shit matters at all. So just enjoy yourself."
, "In every life there are events that reshape one's sense of existence."
+ "Afterward, all is different and the past is dimmed."
, "Maybe we really are made of the same clay, maybe we really are condemned,"
+ "blameless, to the same, identical mediocrity."
, "It is intoxicating joy for the sufferer to look away from his suffering and to forget himself."
, "Just because we're all doomed doesn't mean we can't have a good time."
, "Do you know what punishments I've endured for my crimes, my sins? None."
+ "I am proof of the absurdity of men's most treasured abstractions. A just universe wouldn't tolerate my existence."
, "Life's but a walking shadow, a poor player, that struts and frets his hour upon the stage,"
+ "and then is heard no more; it is a tale told by an idiot, full of sound and fury, signifying nothing."];
